# Generated by Django 5.2.7 on 2026-02-26 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_last_failed_login_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=12345678, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–15 digits, optional + sign).', regex='^\\+?\\d{7,15}$')]),
            preserve_default=False,
        ),
    ]
