# Generated by Django 5.2.7 on 2026-03-02 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter Valid Phone Number, e.g. +923001234567', regex='^\\+?1?\\d{9,15}$')])),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('read', 'Read'), ('resolved', 'Resolved'), ('spam', 'Spam')], db_index=True, default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes -- sirf admin dekh sakta hai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='core_contac_email_cfac76_idx'), models.Index(fields=['status', 'created_at'], name='core_contac_status_15488c_idx')],
            },
        ),
    ]
