# Generated by Django 5.2.7 on 2026-03-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Internal notes -- only admin can see'),
        ),
    ]
