# Generated by Django 5.2.7 on 2026-02-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='badge_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
