# Generated by Django 5.2.7 on 2026-03-04 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_pricingplan_badge_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Comparison Feature',
                'verbose_name_plural': 'Plan Comparison Features',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanComparisonValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('comparison_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='plans.plancomparison')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_values', to='plans.pricingplan')),
            ],
            options={
                'verbose_name': 'Plan Comparison Value',
                'verbose_name_plural': 'Plan Comparison Values',
                'unique_together': {('comparison_feature', 'plan')},
            },
        ),
    ]
