# Generated by Django 5.2.7 on 2026-03-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plancomparison_plancomparisonvalue'),
        ('service', '0004_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancomparison',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_features', to='service.service'),
        ),
    ]
