# Generated by Django 5.2.7 on 2026-02-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Name of the service category', max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL-friendly version of name', max_length=120, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, help_text='Brief description of this category', null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="CSS icon class (e.g., 'fa-code', 'bi-palette')", max_length=50, null=True, verbose_name='Icon Class')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which category appears (lower numbers first)', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently active', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='service_ser_slug_279858_idx'), models.Index(fields=['is_active', 'display_order'], name='service_ser_is_acti_28a711_idx')],
            },
        ),
    ]
