# Generated by Django 5.2.7 on 2026-02-20 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(help_text="Name of the service (e.g., 'Web Development', 'Logo Design')", max_length=200, unique=True, verbose_name='Service Name')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL-friendly version of service name', max_length=220, unique=True, verbose_name='URL Slug')),
                ('service_type', models.CharField(choices=[('development', 'Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('consulting', 'Consulting'), ('support', 'Support'), ('custom', 'Custom')], default='custom', help_text='Type of service being offered', max_length=20, verbose_name='Service Type')),
                ('short_description', models.CharField(help_text='Brief one-line description for listings', max_length=255, verbose_name='Short Description')),
                ('description', models.TextField(help_text='Detailed description of the service', verbose_name='Full Description')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in this service (JSON array)', verbose_name='Features')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='Client requirements for this service (JSON array)', verbose_name='Requirements')),
                ('icon', models.CharField(blank=True, help_text='CSS icon class for this service', max_length=50, null=True, verbose_name='Icon Class')),
                ('thumbnail', models.ImageField(blank=True, help_text='Service thumbnail image', null=True, upload_to='services/thumbnails/%Y/%m/', verbose_name='Thumbnail Image')),
                ('banner_image', models.ImageField(blank=True, help_text='Service banner/hero image', null=True, upload_to='services/banners/%Y/%m/', verbose_name='Banner Image')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='Array of image URLs for service gallery', verbose_name='Gallery Images')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Starting price for this service (0 for custom quote)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base Price')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code (e.g., USD, EUR, GBP)', max_length=3, verbose_name='Currency')),
                ('pricing_model', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate'), ('monthly', 'Monthly Subscription'), ('project', 'Per Project'), ('custom', 'Custom Quote')], default='fixed', help_text='How this service is priced', max_length=20, verbose_name='Pricing Model')),
                ('delivery_time', models.PositiveIntegerField(blank=True, help_text='Estimated delivery time (numeric value)', null=True, verbose_name='Delivery Time')),
                ('delivery_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', help_text='Unit for delivery time', max_length=10, verbose_name='Delivery Unit')),
                ('revisions_included', models.PositiveIntegerField(default=0, help_text='Number of revisions included (0 for unlimited)', verbose_name='Revisions Included')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently offered', verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Display this service in featured section', verbose_name='Is Featured')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which service appears (lower numbers first)', verbose_name='Display Order')),
                ('category', models.ForeignKey(blank=True, help_text='Category this service belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='service.servicecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='service_ser_slug_1d1ace_idx'), models.Index(fields=['is_active', 'is_featured'], name='service_ser_is_acti_026b4c_idx'), models.Index(fields=['category', 'is_active'], name='service_ser_categor_3627b5_idx'), models.Index(fields=['service_type', 'is_active'], name='service_ser_service_d4ec49_idx')],
            },
        ),
    ]
