# Generated by Django 5.2.7 on 2026-03-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload service icon image (PNG, SVG, JPG)', null=True, upload_to='service_icons/', verbose_name='Service Icon'),
        ),
    ]
