# Generated by Django 5.2.7 on 2026-03-09 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_session_3c25be_idx',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='custom_requirements',
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_active'], name='cart_cart_is_acti_96bd76_idx'),
        ),
    ]
