# Generated by Django 5.2.7 on 2026-03-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank='True', choices=[('stripe', 'Stripe'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer')], default='None', max_length=20),
        ),
    ]
