# Generated by Django 5.2.7 on 2026-03-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Anonymous user ka session key — login hone ke baad NULL ho jata hai', max_length=40, null=True),
        ),
    ]
