# Generated by Django 5.2.7 on 2026-03-05 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL-friendly version of product name', max_length=220, unique=True, verbose_name='URL Slug')),
                ('category', models.CharField(choices=[('software', 'Software and Licensing'), ('cybersecurity', 'Cybersecurity'), ('network', 'Network and Data Center'), ('webmail', 'Web Server and Mail Server'), ('hardware', 'Hardware Supply'), ('vm', 'Virtual Machines')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the products', verbose_name='Full Description')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in this Product (JSON array)', verbose_name='Features')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('banner_image', models.ImageField(blank=True, help_text='products banner/hero image', null=True, upload_to='products/banners/%Y/%m/', verbose_name='Banner Image')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='Array of image URLs for service gallery', verbose_name='Gallery Images')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Starting price for this product (0 for custom quote)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base Price')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code (e.g., USD, EUR, GBP)', max_length=3, verbose_name='Currency')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this products is currently active', verbose_name='Is Active')),
                ('is_popular', models.BooleanField(default=False, help_text='Whether this products is popular', verbose_name='Is Popular')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this products is featured or not', verbose_name='Is Featured')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which category appears (lower numbers first)', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'), models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_2fee29_idx'), models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx')],
            },
        ),
    ]
