# Generated by Django 5.2.7 on 2026-03-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='some', help_text='Brief one-line description for listings', max_length=255, verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
